branch-defaults:
  default:
    environment: PROD
# environment-defaults:
#   PROD:
#     branch: null
#     repository: null
global:
  application_name: '%EB_WEB_APP_NAME%'
  default_ec2_keyname: '%SSH_KEY_NAME%'
  default_platform: Docker 18.09.9-ce
  default_region: '%AWS_REGION%'
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
